import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Raleway, Lato} from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-montserrat'});
const raleway = Raleway({ subsets: ["latin"], variable: '--font-raleway' });
const lato = Lato({ weight: ['100', '300', '400', '700', '900'], subsets: ["latin"] , variable: '--font-lato'});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${raleway.variable} ${lato.variable}`}>{children}</body>
    </html>
  );
}
